# Generated by Django 5.1.2 on 2024-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
